# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title BDM
#' @description this function computes the backward degree metric of a graph
#' @param graph A numeric matrix representing the graph adjacency matrix
#' @return A numeric vector containing the backward degree metric for each node
#' @export
BDM <- function(graph) {
    .Call('_SA24204163_BDM', PACKAGE = 'SA24204163', graph)
}

